### ISSUE TITLE
Feature Request - Wider Post Content With Two Columns 

### ISSUE THREAD

**Issue by dimuit86** [thiagorossener/jekflix-template#148]
Hey,

I would like to see more improvements on the JekFlix template. Can I have wider post content without removing the sidebar column? Waiting for v4.0 release.  Anyone's can guide me on this?
![Screenshot_1](https://user-images.githubusercontent.com/79132146/111211308-41f4aa80-85f4-11eb-8991-6a5b4969c9da.png)

**Comment by thiagorossener** [comment]
Hey @dimuit86, I don't intend to change that, but you can.

I imagine you're using the `gem`. If so, you need to create a SCSS in `/assets/css/` called `styles.scss`.

Then add the following:

```scss
---
---

@import "jekflix";

@media (min-width: 37.5rem) {
  .post.two-columns {
    max-width: 100rem;
  }
}

.post-content {
  p,
  h1,
  h2,
  h3,
  h4,
  h5,
  h6,
  ul,
  ol,
  iframe {
    max-width: 100%;
  }
}
```

Adjust as you wish.
