### ISSUE TITLE
Documentation on how to use translations

### ISSUE THREAD

**Issue by lcastrooliveira** [thiagorossener/jekflix-template#80]
I've tried to use the translations.yml file but was unsuccessful after several attempts. Could you provide an example on how to set the translation keys in this file ?

**Comment by thiagorossener** [comment]
Hey @lcastrooliveira, I'm sorry, I should have updated the docs.

You just need to create a `translations.yml` file in `src/yml` and add this:

```
translations:
  text:
    new_post: "Novo Artigo"
    see_also: "Veja também"
    search: "Buscar"
    author: "Autor"
    share: "Compartilhe"
    comments: "Comentários"
  button:
    read_now: "Ler Agora"
    share_on_twitter: "Compartilhe no Twitter"
    share_on_facebook: "Compartilhe no Facebook"
  pagination:
    page: "Página"
    of: "de"
    next_page: "Próxima Página"
    next_post: "Próximo Artigo"
  recommendation:
    text: "Talvez você também curta esse daqui:"
    back_btn: "Voltar para o topo"
  error_404:
    title: "Página não encontrada :("
    message: "Sinto muito, parece que a página que você estava procurando não foi encontada."
    image_alt: "404 - Página não encontrada"
  contact:
    title: "Fale Comigo"
    subject: "Novo contato!"
    submit_btn: "Enviar"
    placeholders:
      name: "Seu nome"
      email: "Seu e-mail"
      message: "Sua mensagem"
    errors:
      locale: "pt"
      empty_name: "Por favor, insira seu nome"
      empty_email: "Por favor, insira seu e-mail"
      invalid_email: "O e-mail deve ser válido"
      empty_message: "Por favor, insira sua mensagem"
    after_send:
      title: "Mensagem enviada!"
      message: "Obrigado por entrar em contato. Responderei assim que for possível."
```
